language: php

dist: trusty
sudo: false

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - MONOLOG_VERSION='^1.13'
  - MONOLOG_VERSION='^2'

before_script:
  - composer update
  - composer require monolog/monolog:$MONOLOG_VERSION

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit
